# Generated by Django 6.0.1 on 2026-02-03 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publimodel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'], message='Apenas arquivos .jpg e .png são permitidos.')]),
        ),
    ]
